# In England the currency is made up of pound, £, and pence, p, and there are eight coins in general circulation:

# 1p, 2p, 5p, 10p, 20p, 50p, £1 (100p) and £2 (200p).

# It is possible to make £2 in the following way:

# 1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p

# How many different ways can £2 be made using any number of coins?

_____

# How many ways can we make 200p?

### The max number of each coin used in a combination is:

- 1p: 200
- 2p: 100
- 5p: 40
- 10p: 20
- 20p: 10
- 50p: 4
- 100p: 2
- 200p: 1

In [73]:
list_combinations = []

for x_200 in [0,1]:
    total_so_far = 200*x_200
    if total_so_far==200:
        list_combinations.append([x_200])
        continue
    for x_100 in range((200-total_so_far)//100+1):
        total_so_far = 200*x_200+100*x_100
        if total_so_far==200:
            list_combinations.append([x_200, x_100])
            continue
        for x_50 in range((200-total_so_far)//50+1):
            total_so_far = 200*x_200+100*x_100+50*x_50
            if total_so_far==200:
                list_combinations.append([x_200, x_100,x_50])
                continue
            for x_20 in range((200-total_so_far)//20+1):
                total_so_far = 200*x_200+100*x_100+50*x_50+20*x_20
                if total_so_far==200:
                    list_combinations.append([x_200, x_100,x_50, x_20])
                    continue
                for x_10 in range((200-total_so_far)//10+1):
                    total_so_far = 200*x_200+100*x_100+50*x_50+20*x_20+10*x_10
                    if total_so_far==200:
                        list_combinations.append([x_200, x_100,x_50, x_20, x_10])
                        continue
                    for x_5 in range((200-total_so_far)//5+1):
                        total_so_far = 200*x_200+100*x_100+50*x_50+20*x_20+10*x_10+5*x_5
                        if total_so_far==200:
                            list_combinations.append([x_200, x_100,x_50, x_20, x_10, x_5])
                            continue
                        for x_2 in range((200-total_so_far)//2+1):
                            total_so_far = 200*x_200+100*x_100+50*x_50+20*x_20+10*x_10+5*x_5+2*x_2
                            if total_so_far==200:
                                list_combinations.append([x_200, x_100,x_50, x_20, x_10, x_5, x_2])
                                continue
                            for x_1 in range((200-total_so_far)+1):
                                total_so_far = 200*x_200+100*x_100+50*x_50+20*x_20+10*x_10+5*x_5+2*x_2+x_1
                                if total_so_far==200:
                                    list_combinations.append([x_200, x_100,x_50, x_20, x_10, x_5, x_2, x_1])

In [68]:
df = pd.DataFrame(list_combinations, columns = [200,100,50,20,10,5,2,1])
df

       200  100  50   20   10   5     2      1
0        0  0.0  0.0  0.0  0.0  0.0   0.0  200.0
1        0  0.0  0.0  0.0  0.0  0.0   1.0  198.0
2        0  0.0  0.0  0.0  0.0  0.0   2.0  196.0
3        0  0.0  0.0  0.0  0.0  0.0   3.0  194.0
4        0  0.0  0.0  0.0  0.0  0.0   4.0  192.0
5        0  0.0  0.0  0.0  0.0  0.0   5.0  190.0
6        0  0.0  0.0  0.0  0.0  0.0   6.0  188.0
7        0  0.0  0.0  0.0  0.0  0.0   7.0  186.0
8        0  0.0  0.0  0.0  0.0  0.0   8.0  184.0
9        0  0.0  0.0  0.0  0.0  0.0   9.0  182.0
10       0  0.0  0.0  0.0  0.0  0.0  10.0  180.0
11       0  0.0  0.0  0.0  0.0  0.0  11.0  178.0
12       0  0.0  0.0  0.0  0.0  0.0  12.0  176.0
13       0  0.0  0.0  0.0  0.0  0.0  13.0  174.0
14       0  0.0  0.0  0.0  0.0  0.0  14.0  172.0
15       0  0.0  0.0  0.0  0.0  0.0  15.0  170.0
16       0  0.0  0.0  0.0  0.0  0.0  16.0  168.0
17       0  0.0  0.0  0.0  0.0  0.0  17.0  166.0
18       0  0.0  0.0  0.0  0.0  0.0  18.0  164.0
19       0  0.0  0.0  0.0  0.0  0.0  19.0  162.0
20       0  0.0  0.0  0.0  0.0  0.0  20.0  160.0
21       0  0.0  0.0  0.0  0.0  0.0  21.0  158.0
22       0  0.0  0.0  0.0  0.0  0.0  22.0  156.0
23       0  0.0  0.0  0.0  0.0  0.0  23.0  154.0
24       0  0.0  0.0  0.0  0.0  0.0  24.0  152.0
25       0  0.0  0.0  0.0  0.0  0.0  25.0  150.0
26       0  0.0  0.0  0.0  0.0  0.0  26.0  148.0
27       0  0.0  0.0  0.0  0.0  0.0  27.0  146.0
28       0  0.0  0.0  0.0  0.0  0.0  28.0  144.0
29       0  0.0  0.0  0.0  0.0  0.0  29.0  142.0
...    ...  ...  ...  ...  ...  ...   ...    ...
73652    0  1.0  1.0  1.0  1.0  2.0   5.0    NaN
73653    0  1.0  1.0  1.0  1.0  3.0   0.0    5.0
73654    0  1.0  1.0  1.0  1.0  3.0   1.0    3.0
73655    0  1.0  1.0  1.0  1.0  3.0   2.0    1.0
73656    0  1.0  1.0  1.0  1.0  4.0   NaN    NaN
73657    0  1.0  1.0  1.0  2.0  0.0   0.0   10.0
73658    0  1.0  1.0  1.0  2.0  0.0   1.0    8.0
73659    0  1.0  1.0  1.0  2.0  0.0   2.0    6.0
73660    0  1.0  1.0  1.0  2.0  0.0   3.0    4.0
73661    0  1.0  1.0  1.0  2.0  0.0   4.0    2.0
73662    0  1.0  1.0  1.0  2.0  0.0   5.0    NaN
73663    0  1.0  1.0  1.0  2.0  1.0   0.0    5.0
73664    0  1.0  1.0  1.0  2.0  1.0   1.0    3.0
73665    0  1.0  1.0  1.0  2.0  1.0   2.0    1.0
73666    0  1.0  1.0  1.0  2.0  2.0   NaN    NaN
73667    0  1.0  1.0  1.0  3.0  NaN   NaN    NaN
73668    0  1.0  1.0  2.0  0.0  0.0   0.0   10.0
73669    0  1.0  1.0  2.0  0.0  0.0   1.0    8.0
73670    0  1.0  1.0  2.0  0.0  0.0   2.0    6.0
73671    0  1.0  1.0  2.0  0.0  0.0   3.0    4.0
73672    0  1.0  1.0  2.0  0.0  0.0   4.0    2.0
73673    0  1.0  1.0  2.0  0.0  0.0   5.0    NaN
73674    0  1.0  1.0  2.0  0.0  1.0   0.0    5.0
73675    0  1.0  1.0  2.0  0.0  1.0   1.0    3.0
73676    0  1.0  1.0  2.0  0.0  1.0   2.0    1.0
73677    0  1.0  1.0  2.0  0.0  2.0   NaN    NaN
73678    0  1.0  1.0  2.0  1.0  NaN   NaN    NaN
73679    0  1.0  2.0  NaN  NaN  NaN   NaN    NaN
73680    0  2.0  NaN  NaN  NaN  NaN   NaN    NaN
73681    1  NaN  NaN  NaN  NaN  NaN   NaN    NaN

[73682 rows x 8 columns]

In [72]:
len(df)

73682

# Answer: 73,682